export const bannerColor = '#f7bacf'
export const aboutMeColor = '#f7bacf'
export const projectsColor = '#66b16c'
export const technologyColor = '#66b16c'
export const artworksColor = '#f7bacf'
export const contactsColor = '#66b16c'